---
version: 2
updates:
  - packageecosystem: bundler
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
